/// Generated by AssetsRefGenerator on 2022/05/06
class Res {
  static const String a = "assets/a.jfif";
  static const String b = "assets/b.jfif";
  static const String c = "assets/c.jpg";
  static const String d = "assets/d.jfif";
  static const String e = "assets/e.jpg";
  static const String loading = "assets/loading.json";
}
