/// Generated by AssetsRefGenerator on 2022/05/07
class Res {
  static const String a = "assets/a.jfif";
  static const String b = "assets/b.jfif";
  static const String c = "assets/c.jpg";
  static const String d = "assets/d.jfif";
  static const String e = "assets/e.jpg";
  static const String f = "assets/f.jpg";
  static const String g = "assets/g.jfif";
  static const String h = "assets/h.jfif";
  static const String i = "assets/i.jpg";
  static const String loading = "assets/loading.json";
}
